"use client";

import { ArrowLeft, ArrowRight, BarChart3, BookOpen, CalendarDays, Check, Download, Flame, Plus, RotateCcw, Search, ShieldCheck, Sparkles, Target, Trash2, UserRound, X, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { AppStore, Idiom, Mistake, Question, Session, View } from "../lib/types";
import { CONTENT_NOTICE } from "../lib/content";
import { formatDate, today } from "../lib/storage";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>;
}

function EmptyState({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return <div className="empty-state"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{description}</p></div>;
}

export function TodayPage({ store, completedPercent, dueCount, daysToExam, beginPractice, showView }: { store: AppStore; completedPercent: number; dueCount: number; daysToExam: number; beginPractice: () => void; showView: (view: View) => void }) {
  const planLabel = `${store.dailyMinutes} 分钟学习计划`;
  return <><PageHeader eyebrow={`${formatDate(today)} · 今日计划`} title={`早上好，${store.user?.nickname || "备考者"}`} description="每天有计划地学习，及时复习真正薄弱的内容。" action={<button className="primary-button" onClick={beginPractice}><Zap size={17} />开始今日训练</button>} />
    <section className="hero-grid"><div className="focus-panel"><div className="panel-topline"><span>今日任务</span><span className="muted">{store.completedToday} / 20 题</span></div><div className="progress-line"><span style={{ width: `${completedPercent}%` }} /></div><div className="focus-main"><div><span className="eyebrow">{planLabel}</span><h2>{store.completedToday ? "保持这个节奏" : "从第一道题开始"}</h2><p>成语填空 · 即时解析 · 错题复习</p></div><strong>{completedPercent}%</strong></div><div className="task-list"><TaskRow icon={<Target size={17} />} title="成语填空训练" note="10 题 · 预计 8 分钟" onClick={beginPractice} /><TaskRow icon={<RotateCcw size={17} />} title="到期错题复习" note={`${dueCount} 题等待复习`} onClick={() => showView("mistakes")} /><TaskRow icon={<BookOpen size={17} />} title="词义快速测试" note="10 个成语 · 预计 8 分钟" onClick={() => showView("vocabulary")} /></div></div><div className="side-stack"><div className="countdown-panel"><CalendarDays size={20} /><span className="eyebrow">距离目标考试</span><strong>{daysToExam}</strong><span>天 · 2028 国考 · {store.region}</span><button className="text-button" onClick={() => showView("settings")}>调整目标 <ArrowRight size={14} /></button></div><div className="weak-panel"><span className="eyebrow">需要优先处理</span><div className="weak-item"><span className="rank">01</span><span>语境判断</span><b>待加强</b></div><div className="weak-item"><span className="rank">02</span><span>近义辨析</span><b>保持练习</b></div></div></div></section>
    <div className="stat-grid"><MiniStat icon={<Check size={17} />} label="本周正确率" value={`${accuracyOf(store)}%`} note="基于站内答题记录" /><MiniStat icon={<Flame size={17} />} label="连续学习" value={`${streakOf(store)} 天`} note="保持每日一练" /><MiniStat icon={<Target size={17} />} label="累计刷题" value={`${store.attempts.length} 题`} note="仅统计站内记录" /><MiniStat icon={<BookOpen size={17} />} label="词库总量" value={`${store.idioms.length}`} note="可追溯编辑词条" /></div>
  </>;
}

function TaskRow({ icon, title, note, onClick }: { icon: React.ReactNode; title: string; note: string; onClick: () => void }) {
  return <button className="task-row" onClick={onClick}><span className="task-icon">{icon}</span><span className="task-copy"><strong>{title}</strong><small>{note}</small></span><ArrowRight size={16} /></button>;
}

function MiniStat({ icon, label, value, note }: { icon: React.ReactNode; label: string; value: string; note: string }) {
  return <div className="mini-stat"><div className="stat-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></div>;
}

export function PracticePage({ question, index, total, selected, setSelected, submitted, submitAnswer, nextQuestion, selectedReasons, toggleReason, sessionResult, beginPractice, showView }: { question?: Question; index: number; total: number; selected: number | null; setSelected: (value: number) => void; submitted: boolean; submitAnswer: () => void; nextQuestion: () => void; selectedReasons: string[]; toggleReason: (reason: string) => void; sessionResult: { total: number; correct: number; seconds: number } | null; beginPractice: () => void; showView: (view: View) => void }) {
  if (sessionResult) return <div className="result-wrap"><div className="result-card"><div className="result-check"><Check size={30} /></div><span className="eyebrow">SESSION COMPLETE</span><h1>这一轮完成了</h1><p>把结果留下，下一次训练会更有针对性。</p><div className="result-stats"><div><strong>{sessionResult.correct}/{sessionResult.total}</strong><span>答对题数</span></div><div><strong>{sessionResult.total ? Math.round(sessionResult.correct / sessionResult.total * 100) : 0}%</strong><span>本轮正确率</span></div><div><strong>{Math.round(sessionResult.seconds / 60)}′</strong><span>总用时</span></div></div><div className="result-actions"><button className="primary-button" onClick={beginPractice}><RotateCcw size={17} />再练一轮</button><button className="secondary-button" onClick={() => showView("today")}>回到今日</button></div></div></div>;
  if (!question) return <EmptyState icon={<BookOpen size={24} />} title="暂无可练习题目" description="请先在题库后台发布题目。" />;
  const isCorrect = selected === question.answer;
  const reasons = ["知识点不会", "词义或概念混淆", "语境判断错误", "排除方法错误", "粗心看错", "时间不足"];
  return <><div className="practice-top"><button className="back-button" onClick={() => showView("today")}><ArrowLeft size={17} />退出训练</button><span className="practice-label">成语填空 · 普通模式</span><span className="practice-counter">{String(index + 1).padStart(2, "0")} <i>/</i> {String(total).padStart(2, "0")}</span></div><div className="practice-progress"><span style={{ width: `${(index / total) * 100}%` }} /></div><div className="question-layout"><article className="question-card"><div className="question-meta"><span>{question.contentStatus === "curated" ? "可追溯内容" : "导入内容"}</span><span>{question.difficulty}</span><span>{question.source}</span></div><h1>{question.stem}</h1><div className="options-list">{question.options.map((option, optionIndex) => <button key={option} className={`option-button ${selected === optionIndex ? "selected" : ""} ${submitted && optionIndex === question.answer ? "correct" : ""} ${submitted && selected === optionIndex && !isCorrect ? "wrong" : ""}`} onClick={() => !submitted && setSelected(optionIndex)}><span className="option-key">{"ABCD"[optionIndex]}</span><span>{option}</span>{submitted && optionIndex === question.answer && <Check size={17} />}{submitted && selected === optionIndex && !isCorrect && <X size={17} />}</button>)}</div>{!submitted ? <button className="primary-button answer-button" disabled={selected === null} onClick={submitAnswer}>提交答案 <ArrowRight size={17} /></button> : <div className={`answer-feedback ${isCorrect ? "is-correct" : "is-wrong"}`}><div className="feedback-heading"><span className="feedback-icon">{isCorrect ? <Check size={18} /> : <X size={18} />}</span><strong>{isCorrect ? "回答正确" : `正确答案：${"ABCD"[question.answer]} · ${question.options[question.answer]}`}</strong></div><p>{question.explanation}</p>{!isCorrect && <div className="reason-picker"><span>这道题错在哪里？</span><div>{reasons.map((reason) => <button key={reason} className={selectedReasons.includes(reason) ? "active" : ""} onClick={() => toggleReason(reason)}>{reason}</button>)}</div></div>}<button className="primary-button answer-button" onClick={nextQuestion}>{index === total - 1 ? "查看本轮结果" : "下一题"}<ArrowRight size={17} /></button></div>}</article><aside className="practice-aside"><div className="aside-card"><span className="eyebrow">答题记录</span><div className="answer-dots">{Array.from({ length: total }, (_, dotIndex) => <span key={dotIndex} className={dotIndex < index ? "done" : dotIndex === index ? "current" : ""}>{dotIndex < index ? <Check size={11} /> : dotIndex + 1}</span>)}</div><p>完成每道题后会即时显示解析，并自动加入你的复习记录。</p></div><div className="aside-card quiet-card"><BookOpen size={18} /><strong>今日建议</strong><p>{CONTENT_NOTICE}</p></div></aside></div></>;
}

export function MistakesPage({ mistakes, questions, dueCount, beginPractice }: { mistakes: Mistake[]; questions: Question[]; dueCount: number; beginPractice: (ids?: string[]) => void }) {
  const [filter, setFilter] = useState<"all" | "due" | "repeat">("all");
  const visible = mistakes.filter((mistake) => filter === "due" ? mistake.dueAt <= today && !mistake.mastered : filter === "repeat" ? mistake.count >= 2 : true);
  return <><PageHeader eyebrow="REVIEW QUEUE" title="错题复习" description="把错误变成下一次答对的线索。" action={<button className="primary-button" disabled={!dueCount} onClick={() => beginPractice(mistakes.filter((item) => item.dueAt <= today && !item.mastered).map((item) => item.questionId))}><RotateCcw size={17} />复习到期错题</button>} /><div className="filter-tabs"><button className={filter === "all" ? "active" : ""} onClick={() => setFilter("all")}>全部错题 <span>{mistakes.length}</span></button><button className={filter === "due" ? "active" : ""} onClick={() => setFilter("due")}>今日待复习 <span>{dueCount}</span></button><button className={filter === "repeat" ? "active" : ""} onClick={() => setFilter("repeat")}>反复错误 <span>{mistakes.filter((item) => item.count >= 2).length}</span></button></div>{visible.length ? <div className="mistake-list">{visible.map((mistake) => { const question = questions.find((item) => item.id === mistake.questionId); if (!question) return null; return <div className="mistake-card" key={mistake.questionId}><div className="mistake-index">{String(mistake.count).padStart(2, "0")}</div><div className="mistake-body"><strong>{question.stem}</strong><div className="mistake-meta"><span>{mistake.count} 次答错</span><span>最近：{formatDate(mistake.lastWrongAt)}</span>{mistake.reasons.map((reason) => <em key={reason}>{reason}</em>)}</div></div><button className="secondary-button compact" onClick={() => beginPractice([mistake.questionId])}>重新练习 <ArrowRight size={15} /></button></div>; })}</div> : <EmptyState icon={<Check size={24} />} title="复习队列是空的" description="完成训练后，答错的题目会自动出现在这里。" />}</>;
}

export function VocabularyPage({ idioms, favoriteIds, toggleFavorite }: { idioms: Idiom[]; favoriteIds: string[]; toggleFavorite: (idiomId: string) => void }) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("全部");
  const [testMode, setTestMode] = useState(false);
  const [testIndex, setTestIndex] = useState(0);
  const [selected, setSelected] = useState<string | null>(null);
  const [score, setScore] = useState(0);
  const [page, setPage] = useState(1);
  const publishedIdioms = idioms.filter((item) => item.status === "published");
  const testIdioms = publishedIdioms.slice(0, 10);
  const categories = useMemo(() => ["全部", ...Array.from(new Set(idioms.map((item) => item.category).filter(Boolean))).sort()], [idioms]);
  const current = testIdioms[testIndex];
  const testOptions = useMemo(() => current ? [current.meaning, ...testIdioms.filter((item) => item.id !== current.id).slice(0, 3).map((item) => item.meaning)] : [], [current, testIdioms]);
  const filtered = publishedIdioms.filter((item) => (item.name.includes(search) || item.meaning.includes(search)) && (category === "全部" || item.category === category));
  const pageCount = Math.max(1, Math.ceil(filtered.length / 30));
  const currentPage = Math.min(page, pageCount);
  const visible = filtered.slice((currentPage - 1) * 30, currentPage * 30);
  useEffect(() => { setPage(1); }, [search, category]);
  if (testMode && current) return <><PageHeader eyebrow="MEANING TEST" title="词义快速测试" description={`第 ${testIndex + 1} / ${testIdioms.length} 题 · 当前得分 ${score}`} action={<button className="secondary-button" onClick={() => setTestMode(false)}>返回词库</button>} /><div className="vocab-test-card"><span className="eyebrow">请选出“{current.name}”的正确释义</span><h2>{current.name}</h2><span className="pinyin">{current.pinyin}</span><div className="test-options">{testOptions.map((option) => <button key={option} className={selected === option ? (option === current.meaning ? "correct" : "wrong") : ""} disabled={Boolean(selected)} onClick={() => { setSelected(option); if (option === current.meaning) setScore((value) => value + 1); }}>{option}</button>)}</div>{selected && <div className="test-feedback"><strong>{selected === current.meaning ? "回答正确" : "再记一次"}</strong><p>{current.meaning}</p><button className="primary-button" onClick={() => { if (testIndex === testIdioms.length - 1) { setTestMode(false); setTestIndex(0); setSelected(null); } else { setTestIndex((value) => value + 1); setSelected(null); } }}>{testIndex === testIdioms.length - 1 ? `完成测试 · ${score} 分` : "下一题"}<ArrowRight size={16} /></button></div>}</div></>;
  return <><PageHeader eyebrow="CURATED VOCABULARY" title="词库" description={`${CONTENT_NOTICE} 当前已发布 ${publishedIdioms.length} 条`} action={<button className="secondary-button" disabled={!testIdioms.length} onClick={() => setTestMode(true)}><BookOpen size={17} />开始词义测试</button>} /><div className="vocab-toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索成语或释义" /></div><select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></div><div className="vocab-grid">{visible.map((item) => <div className="vocab-card" key={item.id}><div className="vocab-card-top"><span className="tag">{item.category}</span><button className={`icon-button ${favoriteIds.includes(item.id) ? "is-favorite" : ""}`} title={favoriteIds.includes(item.id) ? "取消今日复习" : "加入今日复习"} onClick={() => toggleFavorite(item.id)}><Plus size={17} /></button></div><h3>{item.name}</h3><span className="pinyin">{item.pinyin}</span><p>{item.meaning}</p><div className="vocab-example">{item.example}</div><small className="source-note">{item.sourceRef}</small></div>)}</div>{pageCount > 1 && <div className="pagination"><span>共 {filtered.length} 条 · 第 {currentPage} / {pageCount} 页</span><div><button className="secondary-button compact" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)}>上一页</button><button className="secondary-button compact" disabled={currentPage >= pageCount} onClick={() => setPage(currentPage + 1)}>下一页</button></div></div>}</>;
}

export function ProgressPage({ store, accuracy, streak, totalAnswered, onExport }: { store: AppStore; accuracy: number; streak: number; totalAnswered: number; onExport: () => void }) {
  const [range, setRange] = useState<7 | 30 | 0>(7);
  const sessions = range ? store.sessions.slice(0, range) : store.sessions;
  const max = Math.max(...sessions.slice(0, 7).map((session) => session.total), 20);
  return <><PageHeader eyebrow="YOUR RHYTHM" title="学习进度" description="看见稳定积累，也看见下一步该往哪里用力。" action={<button className="secondary-button" onClick={onExport}><Download size={17} />导出记录</button>} /><div className="progress-overview"><div className="big-stat"><span>站内正确率</span><strong>{accuracy}%</strong><p>基于 {totalAnswered} 道已提交题目</p></div><div className="big-stat"><span>连续学习</span><strong>{streak}<small>天</small></strong><p>每天完成一轮练习即可保持</p></div><div className="big-stat"><span>学习阶段</span><strong className="stage-value">{accuracy >= 80 ? "稳定提升" : "基础积累"}</strong><p>目标：2028 国考 · {store.region}</p></div></div><div className="chart-card"><div className="section-heading"><div><span className="eyebrow">SESSION RANGE</span><h2>训练量趋势</h2></div><div className="range-tabs"><button className={range === 7 ? "active" : ""} onClick={() => setRange(7)}>7 天</button><button className={range === 30 ? "active" : ""} onClick={() => setRange(30)}>30 天</button><button className={range === 0 ? "active" : ""} onClick={() => setRange(0)}>全部</button></div></div><div className="bar-chart">{Array.from({ length: 7 }, (_, index) => { const session = sessions[6 - index]; const value = session?.total || 0; return <div className="bar-item" key={index}><span className="bar-value">{value || "·"}</span><div className="bar-track"><span style={{ height: `${Math.max(value ? 12 : 3, value / max * 100)}%` }} /></div><small>{session ? formatDate(session.date).slice(5) : `—${6 - index}`}</small></div>; })}</div></div><div className="analytics-grid"><div className="analytics-card"><div className="section-heading"><h2>模块表现</h2><BarChart3 size={18} /></div><div className="module-line"><span>成语填空</span><div><i style={{ width: `${accuracy}%` }} /></div><b>{accuracy}%</b></div><div className="module-line"><span>词义辨析</span><div><i style={{ width: `${Math.max(0, accuracy - 4)}%` }} /></div><b>{Math.max(0, accuracy - 4)}%</b></div><div className="module-line"><span>语境判断</span><div><i style={{ width: `${Math.max(0, accuracy - 9)}%` }} /></div><b>{Math.max(0, accuracy - 9)}%</b></div></div><div className="analytics-card quote-card"><Sparkles size={18} /><p>“真正有效的备考，不是把每天塞满，而是知道什么值得今天再看一遍。”</p><span>学习记录会帮助你调整下一步任务。</span></div></div></>;
}

export function SettingsPage({ store, setStore, onSaveProfile, onChangePassword, onExport, onDelete, passwordError }: { store: AppStore; setStore: React.Dispatch<React.SetStateAction<AppStore>>; onSaveProfile: (event: React.FormEvent<HTMLFormElement>) => void; onChangePassword: (event: React.FormEvent<HTMLFormElement>) => void; onExport: () => void; onDelete: () => void; passwordError: string }) {
  return <><PageHeader eyebrow="YOUR SPACE" title="账号设置" description="调整目标、学习计划和账号安全设置。" /><div className="settings-grid"><form className="settings-card" onSubmit={onSaveProfile}><div className="section-heading"><div><span className="eyebrow">STUDY PROFILE</span><h2>备考档案</h2></div><UserRound size={18} /></div><label>目标考试<input value="2028 国考" readOnly /></label><label>目标地区<select value={store.region} onChange={(event) => setStore((current) => ({ ...current, region: event.target.value }))}><option>全国</option><option>北京</option><option>上海</option><option>广东</option><option>浙江</option></select></label><label>目标日期<input type="date" value={store.targetDate} onChange={(event) => setStore((current) => ({ ...current, targetDate: event.target.value }))} /></label><label>每日学习时间<select value={store.dailyMinutes} onChange={(event) => setStore((current) => ({ ...current, dailyMinutes: Number(event.target.value) }))}><option value={30}>30 分钟</option><option value={60}>60 分钟</option><option value={120}>120 分钟</option></select></label><button className="primary-button" type="submit"><Check size={17} />保存计划</button></form><div className="settings-card"><div className="section-heading"><div><span className="eyebrow">ACCOUNT SECURITY</span><h2>账号安全</h2></div><ShieldCheck size={18} /></div><form className="password-form" onSubmit={onChangePassword}><label>当前密码<input type="password" name="currentPassword" minLength={6} required /></label><label>新密码<input type="password" name="newPassword" minLength={6} required /></label><label>确认新密码<input type="password" name="confirmPassword" minLength={6} required /></label>{passwordError && <p className="form-error">{passwordError}</p>}<button className="secondary-button" type="submit">更新密码</button></form><div className="setting-action"><div><strong>导出学习记录</strong><span>以 JSON 文件保存答题、错题、计划和设置。</span></div><button className="secondary-button compact" onClick={onExport}><Download size={15} />导出</button></div><div className="setting-action"><div><strong>内容来源</strong><span>{CONTENT_NOTICE}</span></div><span className="status-label">可追溯</span></div><div className="danger-zone"><div><strong>删除账号与数据</strong><span>清除当前浏览器中的全部个人学习记录。</span></div><button className="danger-button" onClick={onDelete}><Trash2 size={15} />清除数据</button></div></div></div></>;
}

export function HelpModal({ onClose }: { onClose: () => void }) {
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal-card help-card" onMouseDown={(event) => event.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">QUICK HELP</span><h2>使用说明</h2></div><button className="icon-button" title="关闭" onClick={onClose}><X size={18} /></button></div><div className="help-list"><p><strong>今日训练</strong>从首页开始一轮题目，提交后会立即显示答案和解析。</p><p><strong>错题复习</strong>答错的题会记录错误原因，并在到期后进入复习队列。</p><p><strong>词义测试</strong>在词库中开始 10 题测试，也可以把词条加入今日复习。</p><p><strong>题库后台</strong>管理员可以导入带来源说明的 CSV，发布前请完成内容校审。</p></div><button className="primary-button" onClick={onClose}>知道了 <Check size={16} /></button></div></div>;
}

function accuracyOf(store: AppStore) { const total = store.attempts.length; return total ? Math.round(store.attempts.filter((attempt) => attempt.correct).length / total * 100) : 0; }
function streakOf(store: AppStore) { return store.sessions.length ? Math.min(30, store.sessions.length + 1) : 0; }
